// This file is generated by the FlutterFire CLI.
// You can regenerate this file by running the FlutterFire CLI again.
// To use this file, run: `flutterfire configure`

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForWeb',
    appId: '1:123456789:web:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'bestmiawi-project',
    authDomain: 'bestmiawi-project.firebaseapp.com',
    databaseURL: 'https://bestmiawi-project.firebaseio.com',
    storageBucket: 'bestmiawi-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6S6UekbaKYAUeMO62MzKibGvaG99UjaU',
    appId: '1:833540188100:android:f77629296d53d96e2ba691',
    messagingSenderId: '833540188100',
    projectId: 'bestmlewi-8691c',
    databaseURL: 'https://bestmlewi-8691c.firebaseio.com',
    storageBucket: 'bestmlewi-8691c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForIOS',
    appId: '1:123456789:ios:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'bestmiawi-project',
    databaseURL: 'https://bestmiawi-project.firebaseio.com',
    storageBucket: 'bestmiawi-project.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForMacOS',
    appId: '1:123456789:macos:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'bestmiawi-project',
    databaseURL: 'https://bestmiawi-project.firebaseio.com',
    storageBucket: 'bestmiawi-project.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForWindows',
    appId: '1:123456789:windows:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'bestmiawi-project',
    databaseURL: 'https://bestmiawi-project.firebaseio.com',
    storageBucket: 'bestmiawi-project.appspot.com',
  );
}
